name: CI/CD Workflow

on:
  push:
    branches:
      - master  # Sesuaikan dengan nama branch utama Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Sesuaikan dengan versi Python yang Anda gunakan

      - name: Install dependencies
        run: |
          pip install -r kebutuhan_library.txt

      - name: Run tests
        run: |
          # Tambahkan perintah untuk menjalankan pengujian aplikasi Anda
          echo "No tests specified"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.Paras_Ulama }}

      - name: Deploy to production server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server "cd /path/to/your/app && git pull && source myenv/bin/activate && pip install -r kebutuhan_library.txt && systemctl restart your-app-service"
